/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutProjectsImport } from './routes/_layout/projects'
import { Route as LayoutKeysImport } from './routes/_layout/keys'
import { Route as LayoutGraphImport } from './routes/_layout/graph'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutProjectsRoute = LayoutProjectsImport.update({
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKeysRoute = LayoutKeysImport.update({
  path: '/keys',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGraphRoute = LayoutGraphImport.update({
  path: '/graph',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/graph': {
      preLoaderRoute: typeof LayoutGraphImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/keys': {
      preLoaderRoute: typeof LayoutKeysImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects': {
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutGraphRoute,
    LayoutKeysRoute,
    LayoutProjectsRoute,
  ]),
])

/* prettier-ignore-end */
