/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authenticatedImport } from './routes/__authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as authenticatedGraphImport } from './routes/__authenticated/graph'

// Create/Update Routes

const authenticatedRoute = authenticatedImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedGraphRoute = authenticatedGraphImport.update({
  path: '/graph',
  getParentRoute: () => authenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated': {
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated/graph': {
      preLoaderRoute: typeof authenticatedGraphImport
      parentRoute: typeof authenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  authenticatedRoute.addChildren([authenticatedGraphRoute]),
])

/* prettier-ignore-end */
